spring:
  application:
    name: session-storage
#  session:
#    store-type: redis # ?? ???? ?????.
#    redis:
#      namespace: pfit:session
#    timeout: 60
#  data:
#    redis:
#      host: localhost
#      port: 6379


