spring:
  application:
    name: session-storage
  session:
    store-type: redis # ?? ???? ?????.
    redis:
      namespace: pfit:session
    timeout: 300
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081
logging:
  level:
    org.springframework.security.web: DEBUG