name: CI/CD using github actions & docker

# event trigger
# main이나 feature 브랜치에 push가 되었을 때 실행
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    # job에서 수행하는 step을 정의하는 곳
    steps:

      # Repository로 부터 CI 수행 서버로 코드를 내려받는 Action
      - uses: actions/checkout@v3

      # gradle caching - 빌드 시간 향상
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # gradle build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build